apiVersion: v1
kind: Service
metadata:
  name: java-aws-eks-pipeline
  labels:
    app: java-aws-eks-pipeline
    service: java-aws-eks-pipeline
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: java-aws-eks-pipeline

---
apiVersion: v1
kind: Service
metadata:
  name: java-aws-eks-pipeline-svc-lb
  labels:
    app: java-aws-eks-pipeline-svc-lb
    service: java-aws-eks-pipeline-svc-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: java-aws-eks-pipeline

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-aws-eks-pipeline
  labels:
    app: java-aws-eks-pipeline
spec:
  selector:
    matchLabels:
      app: java-aws-eks-pipeline
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: java-aws-eks-pipeline
    spec:
      containers:
        - name: java-aws-eks-pipeline
          image: 443370689665.dkr.ecr.us-east-1.amazonaws.com/jpmoraess:6c6536b0916a1d13b6e078807eaccc2c1d95e1d9
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prd"
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always